# 2022/01/12/WED

In [24]:
import torch

In [25]:
t=torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [26]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0],t[1],t[-1])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)


- 그 외에도 slicing도 ndarray처럼 사용 가능
- 2차원 3차원도 ndarray처럼 사용 가능

> ### Broadcasting

In [27]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


- 이렇게 같은 크기뿐만 아니라 Broadcasting을 통해

In [28]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3]])
print(m1+m2)

tensor([[4., 5.]])


- 이렇게 크기가 동일하지 않아도 pytorch가 자동으로 동일한 size로 변환하여 연산 수행 가능

In [29]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


In [30]:
print(m1.shape)

torch.Size([1, 2])


In [31]:
m1

tensor([[1., 2.]])

In [32]:
print(m2.shape)

torch.Size([2, 1])


In [33]:
m2

tensor([[3.],
        [4.]])

- 이렇게 행렬 모양이 다르더라도 m1과 m2를 각각 2x2행렬로 변경하여 덧셈 수행하는 기능도 가능하다
- 이런 Broadcasting 기능은 자동으로 수행되기 때문에 잘못 사용하지 않게 유의하자

In [34]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[3],[4]])
print(m1*m2)
print(m1.mul(m2))

tensor([[ 3.,  6.],
        [12., 16.]])
tensor([[ 3.,  6.],
        [12., 16.]])


- 이때 m2가 Broadcasting되면서 우리가 일반적으로 알고 있는 행렬 연산 수행과는 상이하게 진행됨
- 우리가 알고 있는 행렬 연산을 하기 위해서는

In [35]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[3],[4]])
print(m1.matmul(m2))

tensor([[11.],
        [25.]])


- 이렇게 해야한다.

In [36]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [37]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t.mean(dim=0)) # dim=0을 없애겠다.  (2x2) -> (1x2)
print(t.mean(dim=1)) # dim=1을 없애겠다.  (2x2) -> (2x1)
print(t.mean(dim=-1))

tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [38]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [39]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [50]:
t = torch.FloatTensor([[3,2],[1,4]])
print(t)

tensor([[3., 2.],
        [1., 4.]])


In [51]:
print(t.max())

tensor(4.)


In [53]:
print(t.max(dim=0)) # dim=0 제외하고 각 열에서의 max와 그 때의 index값을 알려줌
print(t.max(dim=0)[0]) # max값
print(t.max(dim=0)[1]) # max값의 index 즉, argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([0, 1]))
tensor([3., 4.])
tensor([0, 1])


In [54]:
print(t.max(dim=1))
print(t.max(dim=1)[0])
print(t.max(dim=1)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([0, 1]))
tensor([3., 4.])
tensor([0, 1])
