# 2022/01/13/THU

> ### View(Reshape)

In [8]:
import numpy as np
import torch
t=np.array([[[0, 1, 2],
            [3, 4, 5]],
          
            [[6, 7, 8],
           [9, 10, 11]]])
ft=torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [9]:
t

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [10]:
print(ft.view([-1,3])) # view사용해서 모양 바꾸자
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


- 두개의 차원으로 변경할 건데 앞 차원은 모르겠고 뒷 차원은 세개의 element를 가질래

In [11]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


- 세개의 차원으로 변경할 건데 첫번째 차원은 아직 모르겠고 두번째 차원과 세번째 차원은 각각 1과3으로 변경해줘

> Squeeze

In [12]:
ft=torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [13]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


- 차원이 줄어들었음
- 1만 압축해주는 것 같음

In [15]:
print(ft.squeeze(dim=0))
print(ft.squeeze(dim=1)) # 해당 차원이 1일 때만!

tensor([[0.],
        [1.],
        [2.]])
tensor([0., 1., 2.])


> Unsqueeze

In [16]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


- 첫번째 차원에 1을 넣자

In [20]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [22]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


- 두번째 차원에 1을 넣자

In [24]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


- -1=(dim=1)

In [26]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


> Type Casting

In [27]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [28]:
print(lt.float())

tensor([1., 2., 3., 4.])


- bool형일 때

In [29]:
bt=torch.ByteTensor([True,True,True])
print(bt)

tensor([1, 1, 1], dtype=torch.uint8)


In [30]:
print(bt.long())
print(bt.float())

tensor([1, 1, 1])
tensor([1., 1., 1.])


> Concatenate

In [31]:
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])

In [33]:
print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


> Stacking

In [34]:
x=torch.FloatTensor([1,4])
y=torch.FloatTensor([2,5])
z=torch.FloatTensor([3,6])

In [37]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [38]:
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


> Ones and Zeros

In [40]:
x=torch.FloatTensor([[0,1,2],[2,1,0]])
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


> In-place Operation

In [41]:
x=torch.FloatTensor([[1,2],[3,4]])

In [47]:
print(x.mul(2))
print(x)
print(x.mul_(2))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


- 즉 언더바를 통해 inplace=True 효과!